### ISSUE TITLE
#bugs List For alpha

### ISSUE THREAD

**Issue by dishapatel010** [yash-dk/TorToolkit-Telegram#91]
- [ ] https://t.me/ttkdisc/20768 + (https://nekobin.com/dusenaneki) [Waiting...Can't Replicate]
- [x] https://t.me/ttkdisc/20767
- [ ] https://t.me/ttkdisc/20747
- [ ] - mega dl on /status + auto status issue + central status
- [x] https://t.me/ttkdisc/20650 
- [x] #98
- [x] https://nekobin.com/zejonizomo recurring
- [x] https://telegra.ph/file/408be98055cc584e7bf68.png When `CENTRAL_UPDATE`=`false` It should be only one & Not central
- [x] #99
- [x] https://nekobin.com/karusigoyo extract archive [used url](https://mega.nz/file/xRgm0AYL#1dT_ip_lVNvYgYmiKCWsZRZhoqUIilvtAelFp-vdrAI)
- [x] Splits for onedrive zipped upload.
- [x] #100

```many more to come```

**Comment by yash-dk** [comment]
- [x]  https://t.me/ttkdisc/20768 + (https://nekobin.com/dusenaneki)
fixed

**Comment by dishapatel010** [comment]
> * [x]   https://t.me/ttkdisc/20768 + (https://nekobin.com/dusenaneki)
>   fixed

using this [fix ](https://github.com/yash-dk/TorToolkit-Telegram/commit/afda35a282917f7fcdc7291d10cf3c226c2da7e2)but still on /clearthumb https://nekobin.com/qexegenuso

**Comment by AmirulAndalib** [comment]
- [x] file selection for both telegram and gdrive is still buggy [Cant Replicate]
- [ ] cannot unzip small zip files with large folders sometimes while trying to do so on hrk reboots the bot....
- [x] while extracting any sorts of archive to gdrive it is extracted like `test.tar` and will make an extra folder inside test.tar with the extracted files
- [x]  should use an **Username:Password** protection for viewing `userdata` and `Downloads` on the web interface.... [not bug will be considered later....]

### for enhancement.....Direct telegram name mentions can be used instead of using `DONE`....

**Comment by dishapatel010** [comment]
> * [ ]  file selection for both telegram and gdrive is still buggy
> * [ ]  cannot unzip small zip files with large folders sometimes while trying to do so on hrk reboots the bot....
> * [ ]  while extracting any sorts of archive to gdrive it is extracted like `test.tar` and will make an extra folder inside test.tar with the extracted files
> * [ ]   should use an **Username:Password** protection for viewing `userdata` and `Downloads` on the web interface....
> 
> ### for enhancement.....Direct telegram name mentions can be used instead of using `DONE`....

Try to link logs so it will be easy to fix bug / compelete the code

**Comment by AmirulAndalib** [comment]
> > * [ ]   file selection for both telegram and gdrive is still buggy
> > * [ ]   cannot unzip small zip files with large folders sometimes while trying to do so on hrk reboots the bot....
> > * [ ]   while extracting any sorts of archive to gdrive it is extracted like `test.tar` and will make an extra folder inside test.tar with the extracted files
> > * [ ]    should use an **Username:Password** protection for viewing `userdata` and `Downloads` on the web interface....
> > 
> > ### for enhancement.....Direct telegram name mentions can be used instead of using `DONE`....
> 
> Try to link logs so it will be easy to fix bug / compelete the code

### i spotted nothing much important on logs it needs code improvement  I believe ....

**Comment by AmirulAndalib** [comment]
@yash-dk can we Use Simple Direct Link generator like slam mirror bot?? 

https://raw.githubusercontent.com/SlamDevs/slam-mirrorbot/master/bot/helper/mirror_utils/download_utils/direct_link_generator.py

i want this feature in alpha

**Comment by gitenvx** [comment]
Some bug fixed in my bot, not alpha btw.
For mention/cc read telethon documentation, already in my bot add cc/mention user

**Comment by gitenvx** [comment]
While extracting name.tar and folder still .tar, you can use .replace() string

**Comment by AmirulAndalib** [comment]
> Some bug fixed in my bot, not alpha btw.
> For mention/cc read telethon documentation, already in my bot add cc/mention user

you should do a pr

**Comment by yash-dk** [comment]
> * [x]  https://telegra.ph/file/408be98055cc584e7bf68.png When `CENTRAL_UPDATE`=`false` It should be only one & Not central

In this, the status is shown but not updated as the CENTRAL UPDATE is false.

**Comment by yash-dk** [comment]
> While extracting name.tar and folder still .tar, you can use .replace() string

Yea.. but if the file is my.all.tar.tar this will give the wrong name 

[This](https://github.com/yash-dk/TorToolkit-Telegram/blob/3b20b4b2197bad2756fe5d9d8e1d98d640dcf291/tortoolkit/utils/zip7_utils.py#L126) solves it

**Comment by yash-dk** [comment]
> @yash-dk can we Use Simple Direct Link generator like slam mirror bot??
> 
> https://raw.githubusercontent.com/SlamDevs/slam-mirrorbot/master/bot/helper/mirror_utils/download_utils/direct_link_generator.py
> 
> i want this feature in alpha

Done.
